# Generated by Django 6.0.3 on 2026-04-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectfile",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("character", "Character"),
                    ("location", "Location"),
                    ("item", "Item"),
                    ("note", "Note"),
                ],
                max_length=20,
            ),
        ),
    ]
