# Generated by Django 6.0.3 on 2026-04-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_add_item_file_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="is_trash",
            field=models.BooleanField(
                default=False,
                help_text="Whether this folder is the project's trash folder.",
            ),
        ),
    ]
