# Generated by Django 6.0.3 on 2026-04-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_add_is_trash"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="include_in_compile",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="projectfile",
            name="include_in_compile",
            field=models.BooleanField(default=True),
        ),
    ]
