# Generated by Django 6.0.3 on 2026-04-05 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_compilelayout"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="pov_character",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pov_folders",
                to="api.projectfile",
            ),
        ),
        migrations.AddField(
            model_name="projectfile",
            name="colour",
            field=models.CharField(blank=True, default="", max_length=7),
        ),
        migrations.AddField(
            model_name="projectfile",
            name="pov_character",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pov_files",
                to="api.projectfile",
            ),
        ),
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("colour", models.CharField(blank=True, default="", max_length=7)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels",
                        to="api.project",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("project", "name")},
            },
        ),
        migrations.AddField(
            model_name="folder",
            name="label",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="labeled_folders",
                to="api.label",
            ),
        ),
        migrations.AddField(
            model_name="projectfile",
            name="label",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="labeled_files",
                to="api.label",
            ),
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("colour", models.CharField(blank=True, default="", max_length=7)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statuses",
                        to="api.project",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "statuses",
                "ordering": ["order"],
                "unique_together": {("project", "name")},
            },
        ),
        migrations.AddField(
            model_name="folder",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="status_folders",
                to="api.status",
            ),
        ),
        migrations.AddField(
            model_name="projectfile",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="status_files",
                to="api.status",
            ),
        ),
    ]
